/**
 * Student api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssignmentStatus } from './assignmentStatus';

export interface AssignmentDtoStudent { 
    id?: number;
    subjectId?: number;
    name?: string;
    description?: string;
    start?: Date;
    deadline?: Date;
    maxScore?: number;
    allowAfterDeadline?: boolean;
    fineAfterDeadline?: number;
    studentAssignmentId?: number;
    studentAssignmentStatus?: AssignmentStatus;
}