export * from './application.service';
import { ApplicationService } from './application.service';
export * from './assignments.service';
import { AssignmentsService } from './assignments.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './lessons.service';
import { LessonsService } from './lessons.service';
export * from './redirect.service';
import { RedirectService } from './redirect.service';
export * from './studentAssignments.service';
import { StudentAssignmentsService } from './studentAssignments.service';
export * from './subject.service';
import { SubjectService } from './subject.service';
export * from './teacher.service';
import { TeacherService } from './teacher.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ApplicationService, AssignmentsService, GroupService, LessonsService, RedirectService, StudentAssignmentsService, SubjectService, TeacherService, UserService];
